# inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - !ruby/regexp /old_*\.rb$/
  RunRailsCops: true
Style/StringLiterals:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false